from setuptools import setup, find_packages

__version__ = "1.1.0"

setup(
    name='monarch_amazon_auto_classifier',
    version=__version__,
    author='Stefan Wojciechowski',
    author_email='stefanwoj89@ucla.edu',
    description='A script to help classify Amazon product transactions in Monarch Money.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/stefanwoj89/monarch-amazon-transaction-categorizer',
    packages=find_packages(),
    install_requires=[
        "aiodns==3.2.0",
        "aiohttp==3.10.11",
        "aiosignal==1.3.1",
        "annotated-types == 0.6.0",
        "anthropic==0.38.0",
        "anyio==4.3.0",
        "attrs==23.2.0",
        "autocommand==2.2.2",
        "backoff==2.2.1",
        "certifi==2024.7.4",
        "cffi==1.16.0",
        "charset-normalizer == 3.3.2",
        "distro==1.9.0",
        "filelock==3.14.0",
        "frozenlist==1.4.1",
        "fsspec==2024.3.1",
        "gql==3.5.0",
        "graphql-core == 3.2.3",
        "h11==0.14.0",
        "httpcore==1.0.5",
        "httpx==0.27.0",
        "huggingface-hub == 0.23.0",
        "idna==3.7",
        "jiter==0.7.0",
        "monarchmoney==0.1.15",
        "multidict==6.0.5",
        "numpy==2.1.3",
        "oathtool==2.3.1",
        "openai==1.53.0",
        "packaging==24.0",
        "pandas==2.2.3",
        "path==16.12.1",
        "pprintpp==0.4.0",
        "pycares==4.4.0",
        "pycparser==2.22",
        "pydantic==2.7.1",
        "pydantic_core==2.18.2",
        "python-dateutil == 2.9.0.post0",
        "pytz==2024.2",
        "PyYAML==6.0.1",
        "requests==2.32.0",
        "six==1.17.0",
        "sniffio==1.3.1",
        "tokenizers==0.19.1",
        "tqdm==4.66.4",
        "typing_extensions==4.11.0",
        "tzdata==2024.2",
        "urllib3==2.2.2",
        "yarl==1.12.0",
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)